### PR TITLE
feat: make queue extendable

### PR DESCRIPTION
**Pull request by Vann-Dev**
because the player class can be extended, I think the queue should also be, so the queue can be saved like in Redis and others

### CODE REVIEW

**Comment by Takiyo0** [comment]
hello, i wanted to implement this, can i do that?

**Comment by Vann-Dev** [comment]
sure, but i just found out that queue in player class can be override

**Comment by Vann-Dev** [comment]
oh nvm, cant

> hello, i wanted to implement this, can i do that?

sure

**Comment by Vann-Dev** [comment]
> hello, i wanted to implement this, can i do that?

sure

**Pull request merged**
